[package]
name = "wksbin"
version = "0.1.0"
authors = ["lrx"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wkslib = {path = "../wkslib"} # 内部crate库依赖
